<?php 

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_650af9038724d',
		'title' => 'Gradebook Definitions',
		'fields' => array(
			array(
				'key' => 'field_650affec36775',
				'label' => 'Quarter 1',
				'name' => '',
				'aria-label' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_650f4e5e20d7d',
				'label' => 'Add Quarter 1 Domains',
				'name' => 'add_quarter_1_domains',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => 'field_650b0c717ccec',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_650f4e5e20d7e',
						'label' => 'Domain Name',
						'name' => 'domain_name',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_650f4e5e20d7d',
					),
					array(
						'key' => 'field_650f4e5e20d7f',
						'label' => 'Domain Percentage',
						'name' => 'domain_percentage',
						'aria-label' => '',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'min' => '',
						'max' => '',
						'placeholder' => '',
						'step' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_650f4e5e20d7d',
					),
					array(
						'key' => 'field_650f4e5e20d80',
						'label' => 'Add Sub Domains',
						'name' => 'add_sub_domains',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'table',
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'button_label' => 'Add Row',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_650f4e5e20d81',
								'label' => 'Sub Domain Name',
								'name' => 'sub_domain_name',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_650f4e5e20d80',
							),
							array(
								'key' => 'field_650f4e5e20d82',
								'label' => 'Sub Domain Percentage',
								'name' => 'sub_domain_percentage',
								'aria-label' => '',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'min' => '',
								'max' => '',
								'placeholder' => '',
								'step' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_650f4e5e20d80',
							),
							array(
								'key' => 'field_650f4e5e20d83',
								'label' => 'Based On',
								'name' => 'based_on',
								'aria-label' => '',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'min' => '',
								'max' => '',
								'placeholder' => '',
								'step' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_650f4e5e20d80',
							),
							array(
								'key' => 'field_650f4e5e20d84',
								'label' => 'From',
								'name' => 'from',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_650f4e5e20d80',
							),
							array(
								'key' => 'field_650f4e5e20d85',
								'label' => 'To',
								'name' => 'to',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_650f4e5e20d80',
							),
							array(
								'key' => 'field_650f4e5e20d86',
								'label' => 'Open Mode',
								'name' => 'open_mode',
								'aria-label' => '',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'Open' => 'Open',
									'Close' => 'Close',
								),
								'default_value' => false,
								'return_format' => 'value',
								'multiple' => 0,
								'allow_null' => 0,
								'ui' => 0,
								'ajax' => 0,
								'placeholder' => '',
								'parent_repeater' => 'field_650f4e5e20d80',
							),
						),
						'parent_repeater' => 'field_650f4e5e20d7d',
					),
),
),
array(
	'key' => 'field_650b001d17d5a',
	'label' => 'Quarter 2',
	'name' => '',
	'aria-label' => '',
	'type' => 'tab',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'placement' => 'top',
	'endpoint' => 0,
),
array(
	'key' => 'field_650f4e26486a5',
	'label' => 'Add Quarter 2 Domains',
	'name' => 'add_quarter_2_domains',
	'aria-label' => '',
	'type' => 'repeater',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'layout' => 'block',
	'pagination' => 0,
	'min' => 0,
	'max' => 0,
	'collapsed' => 'field_650b0c717ccec',
	'button_label' => 'Add Row',
	'rows_per_page' => 20,
	'sub_fields' => array(
		array(
			'key' => 'field_650f4e26486a6',
			'label' => 'Domain Name',
			'name' => 'domain_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'parent_repeater' => 'field_650f4e26486a5',
		),
		array(
			'key' => 'field_650f4e26486a7',
			'label' => 'Domain Percentage',
			'name' => 'domain_percentage',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
			'parent_repeater' => 'field_650f4e26486a5',
		),
		array(
			'key' => 'field_650f4e26486a8',
			'label' => 'Add Sub Domains',
			'name' => 'add_sub_domains',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_650f4e26486a9',
					'label' => 'Sub Domain Name',
					'name' => 'sub_domain_name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650f4e26486a8',
				),
				array(
					'key' => 'field_650f4e26486aa',
					'label' => 'Sub Domain Percentage',
					'name' => 'sub_domain_percentage',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650f4e26486a8',
				),
				array(
					'key' => 'field_650f4e26486ab',
					'label' => 'Based On',
					'name' => 'based_on',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650f4e26486a8',
				),
				array(
					'key' => 'field_650f4e26486ac',
					'label' => 'From',
					'name' => 'from',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650f4e26486a8',
				),
				array(
					'key' => 'field_650f4e26486ad',
					'label' => 'To',
					'name' => 'to',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650f4e26486a8',
				),
				array(
					'key' => 'field_650f4e26486ae',
					'label' => 'Open Mode',
					'name' => 'open_mode',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Open' => 'Open',
						'Close' => 'Close',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_650f4e26486a8',
				),
			),
			'parent_repeater' => 'field_650f4e26486a5',
		),
	),
),
array(
	'key' => 'field_650b001f17d5b',
	'label' => 'Quarter 3',
	'name' => '',
	'aria-label' => '',
	'type' => 'tab',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'placement' => 'top',
	'endpoint' => 0,
),
array(
	'key' => 'field_650f4dddb90b4',
	'label' => 'Add Quarter 3 Domains',
	'name' => 'add_quarter_3_domains',
	'aria-label' => '',
	'type' => 'repeater',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'layout' => 'block',
	'pagination' => 0,
	'min' => 0,
	'max' => 0,
	'collapsed' => 'field_650b0c717ccec',
	'button_label' => 'Add Row',
	'rows_per_page' => 20,
	'sub_fields' => array(
		array(
			'key' => 'field_650f4dddb90b5',
			'label' => 'Domain Name',
			'name' => 'domain_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'parent_repeater' => 'field_650f4dddb90b4',
		),
		array(
			'key' => 'field_650f4dddb90b6',
			'label' => 'Domain Percentage',
			'name' => 'domain_percentage',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
			'parent_repeater' => 'field_650f4dddb90b4',
		),
		array(
			'key' => 'field_650f4dddb90b7',
			'label' => 'Add Sub Domains',
			'name' => 'add_sub_domains',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_650f4dddb90b8',
					'label' => 'Sub Domain Name',
					'name' => 'sub_domain_name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650f4dddb90b7',
				),
				array(
					'key' => 'field_650f4dddb90b9',
					'label' => 'Sub Domain Percentage',
					'name' => 'sub_domain_percentage',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650f4dddb90b7',
				),
				array(
					'key' => 'field_650f4dddb90ba',
					'label' => 'Based On',
					'name' => 'based_on',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650f4dddb90b7',
				),
				array(
					'key' => 'field_650f4dddb90bb',
					'label' => 'From',
					'name' => 'from',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650f4dddb90b7',
				),
				array(
					'key' => 'field_650f4dddb90bc',
					'label' => 'To',
					'name' => 'to',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650f4dddb90b7',
				),
				array(
					'key' => 'field_650f4dddb90bd',
					'label' => 'Open Mode',
					'name' => 'open_mode',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Open' => 'Open',
						'Close' => 'Close',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_650f4dddb90b7',
				),
			),
			'parent_repeater' => 'field_650f4dddb90b4',
		),
	),
),
array(
	'key' => 'field_650b002017d5c',
	'label' => 'Quarter 4',
	'name' => '',
	'aria-label' => '',
	'type' => 'tab',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'placement' => 'top',
	'endpoint' => 0,
),
array(
	'key' => 'field_650b0c557cceb',
	'label' => 'Add Quarter 4 Domains',
	'name' => 'add_quarter_4_domains',
	'aria-label' => '',
	'type' => 'repeater',
	'instructions' => '',
	'required' => 0,
	'conditional_logic' => 0,
	'wrapper' => array(
		'width' => '',
		'class' => '',
		'id' => '',
	),
	'layout' => 'block',
	'pagination' => 0,
	'min' => 0,
	'max' => 0,
	'collapsed' => 'field_650b0c717ccec',
	'button_label' => 'Add Row',
	'rows_per_page' => 20,
	'sub_fields' => array(
		array(
			'key' => 'field_650b0c717ccec',
			'label' => 'Domain Name',
			'name' => 'domain_name',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'parent_repeater' => 'field_650b0c557cceb',
		),
		array(
			'key' => 'field_650b0ca07cced',
			'label' => 'Domain Percentage',
			'name' => 'domain_percentage',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
			'parent_repeater' => 'field_650b0c557cceb',
		),
		array(
			'key' => 'field_650b0ccd38c32',
			'label' => 'Add Sub Domains',
			'name' => 'add_sub_domains',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_650b0cdb38c33',
					'label' => 'Sub Domain Name',
					'name' => 'sub_domain_name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650b0ccd38c32',
				),
				array(
					'key' => 'field_650b0ceb38c34',
					'label' => 'Sub Domain Percentage',
					'name' => 'sub_domain_percentage',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650b0ccd38c32',
				),
				array(
					'key' => 'field_650b0d4538c35',
					'label' => 'Based On',
					'name' => 'based_on',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => '',
					'max' => '',
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650b0ccd38c32',
				),
				array(
					'key' => 'field_650b0d6b38c36',
					'label' => 'From',
					'name' => 'from',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650b0ccd38c32',
				),
				array(
					'key' => 'field_650b0da638c37',
					'label' => 'To',
					'name' => 'to',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_650b0ccd38c32',
				),
				array(
					'key' => 'field_650b0dad38c38',
					'label' => 'Open Mode',
					'name' => 'open_mode',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Open' => 'Open',
						'Close' => 'Close',
					),
					'default_value' => false,
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_650b0ccd38c32',
				),
			),
			'parent_repeater' => 'field_650b0c557cceb',
		),
	),
),
),
'location' => array(
	array(
		array(
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'gradebook_function',
		),
	),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
));

endif;		





/***********************************************************************************/
/***********************************************************************************/
/********************************* Definition Bank ACF Definitions *****************/
/***********************************************************************************/
/***********************************************************************************/

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_662231cfcb850',
		'title' => 'Definition Bank',
		'fields' => array(
			array(
				'key' => 'field_662231d0a1319',
				'label' => 'Add Quarter Domains',
				'name' => 'add_quarter_domains',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'pagination' => 0,
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'button_label' => 'Add Row',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_6622320fc30e2',
						'label' => 'Domain Name',
						'name' => 'domain_name',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_662231d0a1319',
					),
					array(
						'key' => 'field_6622321ac30e3',
						'label' => 'Domain Percentage',
						'name' => 'domain_percentage',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'parent_repeater' => 'field_662231d0a1319',
					),
					array(
						'key' => 'field_66223222c30e4',
						'label' => 'Add Sub Domains',
						'name' => 'add_sub_domains',
						'aria-label' => '',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'layout' => 'table',
						'pagination' => 0,
						'min' => 0,
						'max' => 0,
						'collapsed' => '',
						'button_label' => 'Add Row',
						'rows_per_page' => 20,
						'sub_fields' => array(
							array(
								'key' => 'field_6622322bc30e5',
								'label' => 'Sub Domain Name',
								'name' => 'sub_domain_name',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_66223222c30e4',
							),
							array(
								'key' => 'field_66223235c30e6',
								'label' => 'Sub Domain Percentage',
								'name' => 'sub_domain_percentage',
								'aria-label' => '',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'min' => '',
								'max' => '',
								'placeholder' => '',
								'step' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_66223222c30e4',
							),
							array(
								'key' => 'field_66223247c30e7',
								'label' => 'Based On',
								'name' => 'based_on',
								'aria-label' => '',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'min' => '',
								'max' => '',
								'placeholder' => '',
								'step' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_66223222c30e4',
							),
							array(
								'key' => 'field_66223252c30e8',
								'label' => 'From',
								'name' => 'from',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_66223222c30e4',
							),
							array(
								'key' => 'field_6622325dc30e9',
								'label' => 'To',
								'name' => 'to',
								'aria-label' => '',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'maxlength' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'parent_repeater' => 'field_66223222c30e4',
							),
							array(
								'key' => 'field_66223268c30ea',
								'label' => 'Open Mode',
								'name' => 'open_mode',
								'aria-label' => '',
								'type' => 'select',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'Open' => 'Open',
									'Close' => 'Close',
								),
								'default_value' => false,
								'return_format' => 'value',
								'multiple' => 0,
								'allow_null' => 0,
								'ui' => 0,
								'ajax' => 0,
								'placeholder' => '',
								'parent_repeater' => 'field_66223222c30e4',
							),
						),
						'parent_repeater' => 'field_662231d0a1319',
					),
),
),
),
'location' => array(
	array(
		array(
			'param' => 'post_type',
			'operator' => '==',
			'value' => 'definitions_function',
		),
	),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
));

endif;		