<?php 

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_65075225422a8',
		'title' => 'Subjects',
		'fields' => array(
			array(
				'key' => 'field_6507522583de5',
				'label' => 'Additional Users',
				'name' => 'additional_users',
				'aria-label' => '',
				'type' => 'user',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'role' => array(
					0 => 'student',
				),
				'return_format' => 'array',
				'multiple' => 1,
				'allow_null' => 0,
			),
			array(
				'key' => 'field_65167acfed2e5',
				'label' => 'Removed Users',
				'name' => 'removed_users',
				'aria-label' => '',
				'type' => 'user',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'role' => array(
					0 => 'student',
				),
				'return_format' => 'array',
				'multiple' => 1,
				'allow_null' => 0,
			),
			array(
				'key' => 'field_6507ffe27e0ee',
				'label' => 'Subject Admin',
				'name' => 'subject_admin',
				'aria-label' => '',
				'type' => 'user',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'role' => '',
				'return_format' => 'array',
				'multiple' => 1,
				'allow_null' => 0,
			),
			array(
				'key' => 'field_65095f004e50d',
				'label' => 'Subject Description',
				'name' => 'subject_description',
				'aria-label' => '',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'rows' => '',
				'placeholder' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_6509a2cf0bb30',
				'label' => 'Select Lesson Type',
				'name' => 'select_lesson_type',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'lesson_type_function',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
				),
				'return_format' => 'object',
				'min' => '',
				'max' => 1,
				'elements' => '',
			),
			array(
				'key' => 'field_650aef5314654',
				'label' => 'Select Gradebook Definition',
				'name' => 'select_gradebook_definition',
				'aria-label' => '',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'gradebook_function',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
				),
				'return_format' => 'object',
				'min' => '',
				'max' => 1,
				'elements' => '',
			),
			array(
				'key' => 'field_654ebbb7299fd',
				'label' => 'ATAR',
				'name' => 'atar',
				'aria-label' => '',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'No' => 'No',
					'Yes' => 'Yes',
				),
				'default_value' => '',
				'return_format' => 'value',
				'allow_null' => 0,
				'other_choice' => 0,
				'layout' => 'vertical',
				'save_other_choice' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'subject_function',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

endif;		